/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginpage;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Aditi Pawar
 */
public class ChangeUsername extends javax.swing.JFrame
{
    Connection con;
    PreparedStatement pst;
    /**
     * Creates new form ChangeUsername
     */
    public ChangeUsername()
    {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlbg = new javax.swing.JPanel();
        pnlmain = new javax.swing.JPanel();
        lblhead = new javax.swing.JLabel();
        pnlchng = new javax.swing.JPanel();
        lblold = new javax.swing.JLabel();
        lblpass = new javax.swing.JLabel();
        lblnew = new javax.swing.JLabel();
        lblre = new javax.swing.JLabel();
        txtold = new javax.swing.JTextField();
        txtnew = new javax.swing.JTextField();
        txtre = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        btnUpdate = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Updating UserName");

        pnlbg.setBackground(new java.awt.Color(255, 205, 178));

        pnlmain.setBackground(new java.awt.Color(229, 152, 155));

        lblhead.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblhead.setForeground(new java.awt.Color(139, 40, 73));
        lblhead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhead.setText("CHANGE USERNAME");

        javax.swing.GroupLayout pnlmainLayout = new javax.swing.GroupLayout(pnlmain);
        pnlmain.setLayout(pnlmainLayout);
        pnlmainLayout.setHorizontalGroup(
            pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlmainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblhead, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlmainLayout.setVerticalGroup(
            pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlmainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblhead, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlchng.setBackground(new java.awt.Color(229, 152, 155));

        lblold.setBackground(new java.awt.Color(255, 180, 162));
        lblold.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblold.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblold.setText("Old UserName");
        lblold.setOpaque(true);

        lblpass.setBackground(new java.awt.Color(255, 180, 162));
        lblpass.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblpass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpass.setText("Password");
        lblpass.setOpaque(true);

        lblnew.setBackground(new java.awt.Color(255, 180, 162));
        lblnew.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblnew.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnew.setText("New UserName");
        lblnew.setOpaque(true);

        lblre.setBackground(new java.awt.Color(255, 180, 162));
        lblre.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblre.setText("Re-Enter UserName");
        lblre.setOpaque(true);

        txtold.setBackground(new java.awt.Color(255, 205, 178));

        txtnew.setBackground(new java.awt.Color(255, 205, 178));

        txtre.setBackground(new java.awt.Color(255, 205, 178));

        txtpass.setBackground(new java.awt.Color(255, 205, 178));
        txtpass.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtpassActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(181, 130, 140));
        btnUpdate.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlchngLayout = new javax.swing.GroupLayout(pnlchng);
        pnlchng.setLayout(pnlchngLayout);
        pnlchngLayout.setHorizontalGroup(
            pnlchngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlchngLayout.createSequentialGroup()
                .addGroup(pnlchngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlchngLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(pnlchngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlchngLayout.createSequentialGroup()
                                .addGroup(pnlchngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblnew, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(pnlchngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlchngLayout.createSequentialGroup()
                                .addGroup(pnlchngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblpass, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblold, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(pnlchngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtold)
                                    .addComponent(txtpass, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))))
                    .addGroup(pnlchngLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        pnlchngLayout.setVerticalGroup(
            pnlchngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlchngLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(pnlchngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblold, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtold, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlchngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtpass, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlchngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnew, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnew, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlchngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtre, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        btnback.setBackground(new java.awt.Color(181, 130, 140));
        btnback.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("<");
        btnback.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlbgLayout = new javax.swing.GroupLayout(pnlbg);
        pnlbg.setLayout(pnlbgLayout);
        pnlbgLayout.setHorizontalGroup(
            pnlbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlbgLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(pnlmain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(pnlbgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(pnlchng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlbgLayout.setVerticalGroup(
            pnlbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlbgLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pnlmain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlbgLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(pnlchng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlbgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlbg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlbg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtpassActionPerformed
    {//GEN-HEADEREND:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnUpdateActionPerformed
    {//GEN-HEADEREND:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String oldUsername = txtold.getText().trim();
        String password = new String(txtpass.getPassword()).trim();
        String newUsername = txtnew.getText().trim();
        String reUsername = txtre.getText().trim();

        if (oldUsername.equals("") || password.equals("") || newUsername.equals("") || reUsername.equals("")) 
        {
            JOptionPane.showMessageDialog(null, "Please fill all fields.");
            return;
        }

        if (newUsername.equals(oldUsername)) 
        {
            JOptionPane.showMessageDialog(null, "New username must be different from the old one.");
            return;
        }

        if (!newUsername.equals(reUsername)) 
        {
            JOptionPane.showMessageDialog(null, "New username and re-entered username do not match.");
            return;
        }
        
        try
        {
            String query = "SELECT * FROM users WHERE username = ? AND password = ?";
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/loginapp", "root", "YOUR-PASSWORD");
            pst = con.prepareStatement(query);
            
            pst.setString(1, oldUsername);
            pst.setString(2, password);
            
            ResultSet res = pst.executeQuery();
            if (res.next()) 
            {
                // Username+password correct, perform update
                PreparedStatement pstnew = con.prepareStatement("UPDATE users SET username = ? WHERE username = ?");
                pstnew.setString(1, newUsername);
                pstnew.setString(2, oldUsername);

                int updated = pstnew.executeUpdate();

                if (updated > 0) 
                {
                    JOptionPane.showMessageDialog(null, "Username successfully updated.");
                } 
                else 
                {
                    JOptionPane.showMessageDialog(null, "Failed to update username.");
                }
                pstnew.close();
            } 
            else 
            {
                JOptionPane.showMessageDialog(null, "Invalid old username or password.");
            }
            
            res.close();
            pst.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Exception :: " + e);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnbackActionPerformed
    {//GEN-HEADEREND:event_btnbackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ChangeUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ChangeUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ChangeUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ChangeUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ChangeUsername().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel lblhead;
    private javax.swing.JLabel lblnew;
    private javax.swing.JLabel lblold;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lblre;
    private javax.swing.JPanel pnlbg;
    private javax.swing.JPanel pnlchng;
    private javax.swing.JPanel pnlmain;
    private javax.swing.JTextField txtnew;
    private javax.swing.JTextField txtold;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtre;
    // End of variables declaration//GEN-END:variables
}
